# ~/.config/starship.toml

add_newline = true

[shell]
powershell_indicator = '󰨊'
bash_indicator = ""
fish_indicator = "󰈺"
zsh_indicator = "zsh"
cmd_indicator = ""
unknown_indicator = ""
style = 'blue'
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold green)'

# Change color of Git Branch
[git_branch]
format = '\([ $branch]($style)\)'
style = "bold red"