# ~/.config/starship.toml

add_newline = false


[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = "🔔 "
Alpine = " "
Amazon = "🙂 "
Android = " "
Arch = "󰣇 "
Artix = " "
CentOS = "󱄚 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "🦅 "
Gentoo = "󰣨 "
HardenedBSD = "🛡️ "
Illumos = " "
Linux = "🐧 "
Mabox = "📦 "
Macos = " "
Manjaro = " "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "󰣭 "
NetBSD = "🚩 "
NixOS = " "
OpenBSD = " "
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = " "
OracleLinux = "🦴 "
Pop = " "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "󱄛 "
Redox = "🧪 "
Solus = " "
SUSE = "🦎 "
Ubuntu = "󰕈 "
Unknown = "OS❓"
Windows = " "

[shell]
powershell_indicator = '󰨊'
bash_indicator = ""
fish_indicator = "󰈺"
zsh_indicator = "zh"
cmd_indicator = ""
unknown_indicator = ""
style = 'blue'
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold green)'

# Change color of Git Branch
[git_branch]
format = '\([ $branch]($style)\)'
style = "bold red"